### ISSUE TITLE
GitHub Login Authentication

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/slack-systers-opensource#10] opened 2018-03-17 23:26 UTC
## Description
As a Systers community member, I need to revise existing way of joining [Systers Open Source Slack Inviter](http://systers.io/slack-systers-opensource/) by authenticating users via Github.
For More Information on this please refer, [Arizona Web Dev](https://azwebdevs.org/signin) uses GitHub to authorize.

## Mocks
N.A

### Update [Required]
- [ ] Investigate How you will achieve this?
- [ ] Allowing User to Authenticate via  GITHUB.
### Enhancement to Update [Optional]
- [ ] Fell free to add your Ideas.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Follow AnitaB.org Brand guidelines.
- [ ] Approval by 1 mentor.

## Estimation
 N.A

**Comment by bethanyr** [comment] 2018-07-23 12:56
is this issue a duplicate of https://github.com/systers/slack-systers-opensource/issues/21? Can it be closed?

**Comment by BaaniLeen** [comment] 2018-07-26 15:48
@bethanyr Yes. Yes :)

**Comment by BaaniLeen** [comment] 2018-08-08 14:05
@bethanyr Can we please close this issue? Thanks! :)

**Comment by bethanyr** [comment] 2018-08-08 15:13
Closing this issue since it is a duplicate and has been implemented.

**Closed by bethanyr** 2018-08-08 15:13 UTC
